/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitesRouteImport } from './routes/sites'
import { Route as AudiovisualRouteImport } from './routes/audiovisual'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksPurgeMediaRouteImport } from './routes/api/public/hooks/purge-media'

const SitesRoute = SitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiovisualRoute = AudiovisualRouteImport.update({
  id: '/audiovisual',
  path: '/audiovisual',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPurgeMediaRoute =
  ApiPublicHooksPurgeMediaRouteImport.update({
    id: '/api/public/hooks/purge-media',
    path: '/api/public/hooks/purge-media',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiovisual': typeof AudiovisualRoute
  '/sites': typeof SitesRoute
  '/api/public/hooks/purge-media': typeof ApiPublicHooksPurgeMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiovisual': typeof AudiovisualRoute
  '/sites': typeof SitesRoute
  '/api/public/hooks/purge-media': typeof ApiPublicHooksPurgeMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audiovisual': typeof AudiovisualRoute
  '/sites': typeof SitesRoute
  '/api/public/hooks/purge-media': typeof ApiPublicHooksPurgeMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audiovisual' | '/sites' | '/api/public/hooks/purge-media'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audiovisual' | '/sites' | '/api/public/hooks/purge-media'
  id:
    | '__root__'
    | '/'
    | '/audiovisual'
    | '/sites'
    | '/api/public/hooks/purge-media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudiovisualRoute: typeof AudiovisualRoute
  SitesRoute: typeof SitesRoute
  ApiPublicHooksPurgeMediaRoute: typeof ApiPublicHooksPurgeMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sites': {
      id: '/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof SitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiovisual': {
      id: '/audiovisual'
      path: '/audiovisual'
      fullPath: '/audiovisual'
      preLoaderRoute: typeof AudiovisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/purge-media': {
      id: '/api/public/hooks/purge-media'
      path: '/api/public/hooks/purge-media'
      fullPath: '/api/public/hooks/purge-media'
      preLoaderRoute: typeof ApiPublicHooksPurgeMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudiovisualRoute: AudiovisualRoute,
  SitesRoute: SitesRoute,
  ApiPublicHooksPurgeMediaRoute: ApiPublicHooksPurgeMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
